export const SCROLL_IMAGES = [
  '/models/1.jpg',
  '/models/2.jpg',
  '/models/4.jpg',
  '/models/3.jpg',
  '/models/5.jpg',
  '/models/7.jpg',
  '/models/6.jpg',
  '/models/8.jpg',
  '/models/12.jpg',
  '/models/9.jpg',
  '/models/14.jpg',
  '/models/10.jpg',
  '/models/15.jpg',
  '/models/11.jpg',
  '/models/17.jpg',
  '/models/13.jpg',
  '/models/18.jpg',
  '/models/16.jpg',
  '/models/19.jpg',
  '/models/21.jpg',
  '/models/20.jpg',
  '/models/22.jpg',
  '/models/23.jpg',
  '/models/26.jpg',
  '/models/24.jpg',
  '/models/27.jpg',
  '/models/25.jpg',
  '/models/28.jpg',
  '/models/31.jpg',
  '/models/29.jpg',
  '/models/52.jpg',
  '/models/53.jpg',
  '/models/32.jpg',
  '/models/30.jpg',
  '/models/35.jpg',
  '/models/33.jpg',
  '/models/36.jpg',
  '/models/37.jpg',
  '/models/39.jpg',
  '/models/38.jpg',
  '/models/41.jpg',
  '/models/40.jpg',
  '/models/42.jpg',
  '/models/43.jpg',
  '/models/44.jpg',

  '/models/48.jpg',
  '/models/45.jpg',
  '/models/50.jpg',
  '/models/46.jpg',

  '/models/47.jpg',
  '/models/49.jpg',
  '/models/34.jpg',

  '/models/54.jpg',
].flatMap(url => Array(1).fill({url}));

export const CAROUSEL_SLIDES = [
  {
    image: '/images/chats.svg',
    title: 'Unmatched Alpha',
    description: 'Curated opportunities across the ecosystem, sent directly to you.',
  },
  {
    image: '/images/lst.png',
    title: 'Premium Tools',
    description: 'Curated opportunities across the ecosystem, sent directly to you.',
  },
  {
    image: '/images/portfolio.svg',
    title: 'Portfolio Tracker',
    description: 'With the most advanced portfolio analytics.',
  },
  {
    image: '/images/project.png',
    title: 'Portfolio Snapshots',
    description: 'Real-time alerts on events that pose risk to your portfolio.',
  },
  {
    image: '/images/alerts.svg',
    title: 'Protect Your bags',
    description: 'Real-time alerts on events that pose risk to your portfolio.',
  },

  {
    image: '/images/potential.svg',
    title: 'reach your full potential',
    description: 'Receive recommendations to improve your portfolio.',
  },
];
